jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Clone wiki repo
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Clean wiki repo
        run: |
          shopt -s extglob
          cd wiki
          rm -rf -- !(.git)

      - name: Copy files to wiki
        run: |
          rsync -av --exclude .git --exclude wiki --exclude .github ./ ./wiki/

      - name: Commit & Push to Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync main repo to wiki [auto]" || echo "No changes to commit"
          git push

